-- ─────────────────────────────────────────────────────────────────────────────
-- Membership terms & conditions slot in club_settings
-- ─────────────────────────────────────────────────────────────────────────────

alter table public.club_settings
  add column if not exists contact_email                text,
  add column if not exists membership_terms_source      text not null default 'default'
    check (membership_terms_source in ('default', 'custom')),
  add column if not exists membership_terms_reviewed    boolean not null default false,
  add column if not exists membership_terms_updated_at  timestamptz,
  add column if not exists membership_terms_content     text,
  add column if not exists membership_terms_file_path   text,
  add column if not exists membership_terms_file_name   text;

-- Allow anonymous users to read club_settings (needed for /apply and /terms public pages)
drop policy if exists "public read club settings" on public.club_settings;
create policy "public read club settings"
  on public.club_settings for select
  using (true);

-- Seed the default Focal Point template into all existing rows
update public.club_settings
set membership_terms_content = '
<h2>[[Club Name]] — Membership Terms &amp; Conditions</h2>
<p>Last updated [[Current Year]]<br>[[Club Location]]</p>

<h3>1. Membership eligibility</h3>
<p>Membership in [[Club Name]] is open to any person with a genuine interest in photography, regardless of skill level. Applications are reviewed by the club executive and membership takes effect upon payment of the applicable annual dues.</p>

<h3>2. Membership fees and renewal</h3>
<p>Annual membership dues are set by the club executive and are payable at the start of each season. Membership lapses automatically if dues remain unpaid after 30 days of the renewal date. No refunds are provided for partial-year memberships unless otherwise agreed by the executive.</p>

<h3>3. Code of conduct</h3>
<p>Members are expected to engage with fellow members, guests, and judges in a respectful and constructive manner. Conduct that is discriminatory, harassing, threatening, or otherwise disruptive — whether in person or online — may result in suspension or termination of membership at the discretion of the club executive.</p>

<h3>4. Competition rules and image originality</h3>
<p>All images submitted to [[Club Name]] competitions must be the original work of the submitting member. The member must have taken the photograph and must hold the copyright. Post-processing and compositing are permitted unless otherwise stated in competition rules; however, AI-generated images or images substantially generated by another person are not eligible. Misrepresentation of authorship will result in immediate disqualification and may result in permanent termination of membership.</p>

<h3>5. Image use by the club</h3>
<p>By submitting images to competitions or club-organised events, members grant [[Club Name]] a non-exclusive, royalty-free right to display those images in club galleries, newsletters, social media accounts, and promotional materials, including publicly accessible channels. Attribution will be provided wherever practical. Members may withdraw this permission at any time by contacting the club at [[Club Contact Email]].</p>

<h3>6. Privacy and data handling</h3>
<p>Member personal information (including name, email address, and contact details) is collected solely for the administration of club membership and events. This information is not sold or shared with third parties except as required by law. Members may request access to their personal data, or ask for it to be corrected or deleted, by contacting [[Club Contact Email]].</p>

<h3>7. Suspension and termination</h3>
<p>The club executive may suspend or terminate a membership for breach of these terms, failure to pay dues, or conduct deemed contrary to the club&apos;s best interests. The member will be notified in writing and given a reasonable opportunity to respond before any final decision is made.</p>

<h3>8. Amendments to these terms</h3>
<p>[[Club Name]] reserves the right to amend these membership terms at any time. Members will be notified of material changes by email. Continued membership following such notification constitutes acceptance of the revised terms.</p>

<p>If you have any questions about these terms, please contact us at [[Club Contact Email]].</p>
'
where membership_terms_content is null;
